### ISSUE TITLE
有两个型号设备都没有这个字段，其中远程调试荣耀7i 双4G 确实没有whiteList字段

### ISSUE THREAD

**Issue by liufsd** [llew2011/HuaWeiVerifier#1]
![image](https://user-images.githubusercontent.com/1910405/36627790-36af68b2-1983-11e8-9272-929b405718e9.png)

**Comment by liufsd** [comment]
但是确实不能注册超过500个，超过就crash。不知道这个whiteList字段在哪里了的。

**Comment by llew2011** [comment]
已修复

**Comment by liufsd** [comment]
明天我试试

**Comment by liufsd** [comment]
这两台设备测试通过。感谢。感谢。
