### ISSUE TITLE
Android 5.1.1,level 22 

### ISSUE THREAD

**Issue by liufsd** [llew2011/HuaWeiVerifier#3]
华为 FDR A03L
华为 FDR A01W
华为 PLE 703L
华为 M2 A01L
这几台还是有crash上报。

线上用的是1.0.4版本。

不知道您这个1.0.6的版本，修复了么？

**Comment by llew2011** [comment]
使用1.0.6版本

**Comment by liufsd** [comment]
您好
华为 FDR A01W 
依旧有crash上报。
