### ISSUE TITLE
Hook有概率不成功.

### ISSUE THREAD

**Issue by zx98cv12** [llew2011/HuaWeiVerifier#6]
放在Applicaton中初始化有概率不能成功的写入白名单.具体为什么失败我也不是很清楚.但是放在Activity中初始化的话基本都成功.ANE_AL00,LLD-AL20,RVL-AL09这几个型号的会有这种情况.

**Comment by MIkeeJY** [comment]
暂未发现，我也是放在application里的，不过一定要放在主进程去hook，不知道您出现的问题是不是有多个进程啊？

**Comment by llew2011** [comment]
@zx98cv12  我这边的做法和@MIkeeJY  是一样的，暂时没发现hook不成功的case

**Comment by zx98cv12** [comment]
> @ zx98cv12 我这边的做法和@MIkeeJY 是一样的，暂时没发现钩不成功的情况下

感谢你的回复,我这边也只是在云真机上测试发现的.手上的手机是可以的.
