### ISSUE TITLE
android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by yghysdr** [llew2011/HuaWeiVerifier#7]
java.lang.reflect.UndeclaredThrowableException:
--
2 $Proxy5.activityStopped(Unknown Source)
3 ......
4 Caused by:
5 android.os.TransactionTooLargeException:data parcel size 533652 bytes
6 android.os.BinderProxy.transactNative(Native Method)
7 android.os.BinderProxy.transact(Binder.java:1147)
8 android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4005)
9 java.lang.reflect.Method.invoke(Native Method)
10 com.llew.huawei.verifier.LoadedApkHuaWei$V28VerifierImpl$AmsInvocationHandler.invoke(LoadedApkHuaWei.java:136)
11 java.lang.reflect.Proxy.invoke(Proxy.java:1006)
12 $Proxy5.activityStopped(Unknown Source)
13 android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
14 android.os.Handler.handleCallback(Handler.java:891)
15 android.os.Handler.dispatchMessage(Handler.java:102)
16 android.os.Looper.loop(Looper.java:207)
17 android.app.ActivityThread.main(ActivityThread.java:7470)
18 java.lang.reflect.Method.invoke(Native Method)
19 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
20 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by llew2011** [comment]
当前库只是hook相关函数，报出TransactionTooLargeException的异常是业务传递参数超出了Binder的限制
