### ISSUE TITLE
Galaxy机型崩溃

### ISSUE THREAD

**Issue by zyj1609wz** [llew2011/HuaWeiVerifier#8]
会造成其他机型崩溃，大佬给看看

![Lark20200506101741](https://user-images.githubusercontent.com/7359324/81133062-1ab86000-8f83-11ea-95b4-cf0dfd85c3de.png)
![Lark20200506101706](https://user-images.githubusercontent.com/7359324/81133057-15f3ac00-8f83-11ea-83a4-5eb0f52ca221.png)

**Comment by llew2011** [comment]
看日志不像是该库引起的，你查下reportSizeConfi***这个错误，另外如果确定是该库引起的，在调用的地方判断下是否是华为设备，是华为的设备再调用
